/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export function debugSocketInfo(): void
export function getNetworkInterface(): ExternalObject<Array<NetworkInterface>>
